# .github/FUNDING.yml

# Link direto para receber doações via PayPal de forma pura e direta
custom: ['https://www.paypal.com/donate/?business=LE69LGH4RB7RA&no_recurring=0&item_name=Criando+ferramentas+de+seguran%C3%A7a+digital+e+Intelig%C3%AAncia+Artificial+open-source%2C+locais+e+focadas+em+privacidade.&currency_code=BRL']
